import { GameMode, Scenario } from '../types';

// GENERAL POOL SCENARIOS - 500 BACKUP SCENARIOS
// Called when the 200 per type is consumed
// Mix of all categories - Universal red flags and green flags
// Difficulty: SUPER HARD - Tricky scenarios that aren't immediately obvious

export const GENERAL_POOL_SCENARIOS: Scenario[] = [
  // ========== RED FLAGS (350) ==========
  
  // Universal Manipulation & Control Red Flags (50)
  { text: "Sinabi niya na 'Kung mahal mo ako, gagawin mo to'. Gamit ang love as bargaining chip.", isRedFlag: true, wisdom: "Emotional blackmail! Love is not currency! Wag mong i-trade ang dignity mo para sa pagmamahal!", category: GameMode.TEENS },
  { text: "Laging may excuse kung bakit hindi niya kaya mag-commit pero gustong gusto niya na committed ka sa kanya.", isRedFlag: true, wisdom: "One-way commitment! Kung hindi kaya mag-commit, bakit hinihingian ka? User yan!", category: GameMode.YOUNG_ADULT },
  { text: "Pinapakita ang phone pag may chat pero biglang nag-delete ng convo habang pinapakita.", isRedFlag: true, wisdom: "Selective transparency! Delete habang pinapakita? May tinatago yang hindi mo dapat makita!", category: GameMode.ADULT },
  { text: "Kinukumbinsi ka na 'wala ka namang magiging ibang choice' kaya dun ka na lang sa kanya.", isRedFlag: true, wisdom: "Scarcity manipulation! Marami pang iba diyan! Wag mong tanggapin ang settling!", category: GameMode.TEENS },
  { text: "Nagbibigay ng silent treatment pag hindi mo ginawa ang gusto niya, walang explanation.", isRedFlag: true, wisdom: "Emotional punishment! Hindi ka bata na pinarurusahan ng timeout! Communicate!", category: GameMode.YOUNG_ADULT },
  { text: "Sinisisi ka sa emotions niya. 'Nagagalit ako dahil sa ginawa mo' kahit hindi naman reasonable.", isRedFlag: true, wisdom: "Blame shifting emotions! Responsible siya sa sarili niyang feelings, hindi ikaw!", category: GameMode.ADULT },
  { text: "Laging 'joke lang' pag may sinabi na nakakasakit. 'Ang sensitive mo naman'.", isRedFlag: true, wisdom: "Gaslighting jokes! Kung joke, bakit hindi nakakatawa? Insult na may excuse!", category: GameMode.TEENS },
  { text: "Nag-iinarte pag may attention ka sa iba kahit sa parents o kapatid mo.", isRedFlag: true, wisdom: "Jealous sa family? Possessive to the extreme! Family is family!", category: GameMode.YOUNG_ADULT },
  { text: "Pinupuna lahat ng ginagawa mo - luto, damit, trabaho, hobbies. Walang tama.", isRedFlag: true, wisdom: "Chronic critic! Walang positive na sinasabi? Draining yan mentally!", category: GameMode.ADULT },
  { text: "Pag may sinabi kang concern, binabaligtad at siya na ang victim.", isRedFlag: true, wisdom: "DARVO master! Deny, Attack, Reverse Victim Offender. Classic manipulation!", category: GameMode.TEENS },
  { text: "Hindi ka pinapayagang magkaroon ng sariling opinyon. 'Ako na bahala sa iniisip mo'.", isRedFlag: true, wisdom: "Thought control! May sarili kang utak, gamitin mo!", category: GameMode.YOUNG_ADULT },
  { text: "Kinukontrol ang schedule mo. 'Bakit ka pupunta dyan? Sino kasama mo?'", isRedFlag: true, wisdom: "Schedule control! Independent adult ka, hindi preso na may visiting hours!", category: GameMode.ADULT },
  { text: "Nag-iiba ng kwento depende sa audience. Iba ang version sa friends, iba sayo.", isRedFlag: true, wisdom: "Truth bender! Pag iba-iba ang story, may sinungaling sa grupo!", category: GameMode.TEENS },
  { text: "Gusto niyang dependent ka sa kanya emotionally, financially, socially.", isRedFlag: true, wisdom: "Creating dependency! Para hindi ka makawala, ginawang need mo siya sa lahat!", category: GameMode.YOUNG_ADULT },
  { text: "Binabaliktad ang history niyo. 'Hindi mo sinabi yan, gawa-gawa mo lang'.", isRedFlag: true, wisdom: "Memory manipulation! Trust your memories! Gaslighting yan!", category: GameMode.ADULT },
  { text: "Sinasabi na 'Di ko kailangan ng iba, ikaw lang'. Pero bakit ganun, ikaw need ng iba?", isRedFlag: true, wisdom: "Isolation setup! Gusto niyang ikaw lang ang buong mundo niya para controlled ka!", category: GameMode.TEENS },
  { text: "Pag nagkamali siya, 'Tao lang' ang excuse. Pag ikaw, walang patawad.", isRedFlag: true, wisdom: "Double standard forgiveness! Pareho kayong tao, pareho dapat ang standard!", category: GameMode.YOUNG_ADULT },
  { text: "Laging nagpapaawa para makuha ang gusto. 'Kung alam mo lang pinagdadaanan ko'.", isRedFlag: true, wisdom: "Pity play! Sympathy should not be used as manipulation tool!", category: GameMode.ADULT },
  { text: "Kinukuwestiyon ang mental health mo pag may reklamo ka. 'Baka kailangan mo ng therapy'.", isRedFlag: true, wisdom: "Questioning sanity! Valid ang concerns mo, wag ka magpadala sa gaslighting!", category: GameMode.TEENS },
  { text: "May 'rules' siya sayo pero siya exempt. 'Iba kasi ako, okay lang sakin'.", isRedFlag: true, wisdom: "Rules for thee, not for me! Fairness dapat, hindi double standard!", category: GameMode.YOUNG_ADULT },

  // Communication & Honesty Red Flags (50)
  { text: "Kapag may problema, naglalabas siya ng frustration sa iba - strangers online, service workers.", isRedFlag: true, wisdom: "Displaced anger! Kung ganyan siya sa iba pag stressed, ikaw ang susunod!", category: GameMode.ADULT },
  { text: "Hindi nagbabasa ng mensahe mo ng maayos. 'K' lang reply sa mahabang kwento mo.", isRedFlag: true, wisdom: "Minimal effort! Kung di ka ma-engage sa chat, paano sa real life?", category: GameMode.TEENS },
  { text: "Nagsisinungaling kahit sa maliit na bagay. 'Kumain na ako' pero halata namang hindi.", isRedFlag: true, wisdom: "Small lies, big pattern! Pag maliit pinagsisisinungaling, paano ang malaki?", category: GameMode.YOUNG_ADULT },
  { text: "Laging 'seen' ang messages mo pero hours o days bago mag-reply. Active naman sa socmed.", isRedFlag: true, wisdom: "Selective availability! Time para mag-scroll, walang time mag-reply sayo?", category: GameMode.ADULT },
  { text: "Binabalita sa buong mundo ang mga away niyo bago pa kayo mag-usap ng maayos.", isRedFlag: true, wisdom: "Public airing! Private issues should be discussed privately first!", category: GameMode.TEENS },
  { text: "Laging defensive. Normal na tanong, parang inquisition ang reaction.", isRedFlag: true, wisdom: "Over-defensiveness! Kung walang tinatago, bakit parang cornered siya?", category: GameMode.YOUNG_ADULT },
  { text: "Hindi nagsa-share ng thoughts or feelings. 'Okay lang ako' kahit halata namang hindi.", isRedFlag: true, wisdom: "Emotional unavailability! Paano magkakaroon ng connection kung walang sharing?", category: GameMode.ADULT },
  { text: "Pag tinanong mo kung nasaan siya, laging vague. 'Dito lang' - saan?", isRedFlag: true, wisdom: "Vague answers! Kung wala namang tinatago, bakit hindi ma-specific?", category: GameMode.TEENS },
  { text: "Laging may 'version' ng kwento para sa iba't ibang tao. Nahihirapan mong sundan.", isRedFlag: true, wisdom: "Story inconsistency! Truth is consistent, lies need versions!", category: GameMode.YOUNG_ADULT },
  { text: "Nag-aayos ng away by pretending nothing happened. Walang actual resolution.", isRedFlag: true, wisdom: "Rug sweeping! Walang closure, nag-pile up lang ang issues!", category: GameMode.ADULT },
  { text: "Binabasa ang private messages mo tapos nagagalit sa nakita kahit out of context.", isRedFlag: true, wisdom: "Snooping then judging! Privacy violation plus jumping to conclusions!", category: GameMode.TEENS },
  { text: "Laging interrupted ka pag nagsasalita. Kailangan lagi siyang mauna.", isRedFlag: true, wisdom: "Conversation dominator! Dapat may turn ka rin magsalita!", category: GameMode.YOUNG_ADULT },
  { text: "'Hindi mo gets' lagi ang sagot pag nagtatanong ka. Instead of explaining.", isRedFlag: true, wisdom: "Dismissive responses! Kung di mo gets, turuan ka, hindi i-dismiss!", category: GameMode.ADULT },
  { text: "Nag-post ng sad quotes about relationship problems bago ka pa kinausap.", isRedFlag: true, wisdom: "Passive-aggressive posting! Social media drama over actual communication!", category: GameMode.TEENS },
  { text: "Laging may 'pero' sa sorry. 'Sorry pero kung hindi ka ganyan...'", isRedFlag: true, wisdom: "Conditional apology! Real sorry has no conditions!", category: GameMode.YOUNG_ADULT },
  { text: "Inaayawan ang deep conversations. 'Ang bigat naman, chill lang tayo'.", isRedFlag: true, wisdom: "Depth avoidance! Healthy relationships need deep talks sometimes!", category: GameMode.ADULT },
  { text: "Kapag may problema ka, binabalewala. 'Ang OA mo naman, ganun talaga'.", isRedFlag: true, wisdom: "Invalidation! Your feelings are valid, wag magpadismiss!", category: GameMode.TEENS },
  { text: "Sinasabi ang isang bagay pero ang body language iba. Confusing signals.", isRedFlag: true, wisdom: "Mixed signals! Words and actions should match!", category: GameMode.YOUNG_ADULT },
  { text: "Laging distracted pag kausap mo - phone, TV, game. 'Ha? Ano sinabi mo?'", isRedFlag: true, wisdom: "Half-listening! Full attention is basic respect in conversation!", category: GameMode.ADULT },
  { text: "Pag may favor na kailangan, super sweet. After makuha, balik sa cold.", isRedFlag: true, wisdom: "Transactional sweetness! Nice only when needed? User yan!", category: GameMode.TEENS },

  // Financial & Responsibility Red Flags (50)
  { text: "Hiram ng hiram ng pera pero laging may post ng bagong sapatos o gadget.", isRedFlag: true, wisdom: "Priority problem! May pang-luho, walang pang-bayad? Wrong priorities!", category: GameMode.YOUNG_ADULT },
  { text: "Lahat ng date ikaw nagbabayad kasi 'next time naman siya'. Next time never comes.", isRedFlag: true, wisdom: "One-sided treats! Alternating dapat, hindi laging ikaw!", category: GameMode.ADULT },
  { text: "Nangungutang sa friends mo kahit di pa niya kilala ng mabuti.", isRedFlag: true, wisdom: "Boundary crossing! Nahihiya ka na for them sa friends mo!", category: GameMode.TEENS },
  { text: "Walang savings kahit may stable income. 'YOLO lang' ang philosophy sa pera.", isRedFlag: true, wisdom: "Financial immaturity! YOLO pero magdudusa kayo pareho pag may emergency!", category: GameMode.YOUNG_ADULT },
  { text: "Gusto mo siya laging libre pero hindi siya magre-reciprocate ever.", isRedFlag: true, wisdom: "Freeloader! Relationship should have give and take, not just take!", category: GameMode.ADULT },
  { text: "May utang sayo na 'nalimutan' niya. Pag siningil, siya pa galit.", isRedFlag: true, wisdom: "Selective memory! Utang dapat binabayad, hindi nilalasing!", category: GameMode.TEENS },
  { text: "Lahat ng financial problems niya, kasalanan ng iba. Boss, parents, economy.", isRedFlag: true, wisdom: "No financial accountability! Lahat may kasalanan except siya?", category: GameMode.YOUNG_ADULT },
  { text: "Nagamit ang savings niyo para sa 'investment' na hindi naman napag-usapan.", isRedFlag: true, wisdom: "Financial infidelity! Shared money needs shared decision!", category: GameMode.ADULT },
  { text: "Expensive ang taste pero walang budget na match. Gusto mo maging provider.", isRedFlag: true, wisdom: "Champagne taste, beer budget! Tapos ikaw sasalo?", category: GameMode.TEENS },
  { text: "Ayaw mag-work kasi 'may trauma sa previous job'. Years na, trauma pa rin.", isRedFlag: true, wisdom: "Work avoidance! Healing is process pero effort din needed!", category: GameMode.YOUNG_ADULT },
  { text: "Lahat ng gamit niyo, sa pangalan mo. Siya walang liability sa kahit ano.", isRedFlag: true, wisdom: "Avoiding responsibility! Pag nag-break, ikaw lang may problema!", category: GameMode.ADULT },
  { text: "Nagko-complain tungkol sa bills pero hindi naman tumutulong bayaran.", isRedFlag: true, wisdom: "Complaining without contributing! Walang karapatan mag-reklamo kung walang ambag!", category: GameMode.TEENS },
  { text: "May secret credit card na nalaman mo lang nung may debt na collection agent.", isRedFlag: true, wisdom: "Hidden debts! Financial secrets destroy trust completely!", category: GameMode.YOUNG_ADULT },
  { text: "Nagagalit pag tinatanong tungkol sa pera. 'Bakit ba, accountant mo ba ako?'", isRedFlag: true, wisdom: "Defensive about money! Transparency should be normal in relationships!", category: GameMode.ADULT },
  { text: "Laging may 'business idea' na need ng capital mo pero walang business plan.", isRedFlag: true, wisdom: "Dreamer without action! Ideas without plans are just fantasies!", category: GameMode.TEENS },
  { text: "Pera mo 'atin', pera niya 'akin'. Double standard sa finances.", isRedFlag: true, wisdom: "Financial double standard! Sharing should be mutual!", category: GameMode.YOUNG_ADULT },
  { text: "Gusto ng expensive gifts pero yung binibigay sayo, discount or libre lang.", isRedFlag: true, wisdom: "Gift imbalance! Effort and budget should be somewhat matched!", category: GameMode.ADULT },
  { text: "Hindi marunong mag-budget. Laging ubos bago pa mag-sahod.", isRedFlag: true, wisdom: "Budget blindness! Money management is basic adulting!", category: GameMode.TEENS },
  { text: "Nangungutang sa pamilya mo kahit hindi mo pa sinasabi na okay.", isRedFlag: true, wisdom: "Overstepping with family! Your family is not their ATM!", category: GameMode.YOUNG_ADULT },
  { text: "Lahat ng luho, priority. Necessities, 'bahala na'.", isRedFlag: true, wisdom: "Misplaced priorities! Needs before wants, basic yan!", category: GameMode.ADULT },

  // Trust & Loyalty Red Flags (50)
  { text: "May 'close friend' na di mo kilala at laging sila nagcha-chat late night.", isRedFlag: true, wisdom: "Suspicious friendship! Kung walang mali, bakit tago?", category: GameMode.TEENS },
  { text: "Laging may bagong 'friend' na opposite gender na super close agad.", isRedFlag: true, wisdom: "Rotating 'friends'! Pattern of getting close to potential replacements!", category: GameMode.YOUNG_ADULT },
  { text: "Sinasabi na single sa dating apps kahit kayo na. 'Nakalimutan i-delete'.", isRedFlag: true, wisdom: "Still shopping! Nakalimutan? Ilang buwan na, nakalimutan pa rin?", category: GameMode.ADULT },
  { text: "Pinagtatanggol ang mga taong nang-aaway sayo. 'Baka naman may point sila'.", isRedFlag: true, wisdom: "Siding against you! Partner should be your ally, not the opposition!", category: GameMode.TEENS },
  { text: "May secret socmed accounts na nalaman mo by accident.", isRedFlag: true, wisdom: "Hidden accounts! Kung walang issue, bakit may secret?", category: GameMode.YOUNG_ADULT },
  { text: "Laging kinukumpara ka sa ex. 'Si ex ganito, ikaw ganyan'.", isRedFlag: true, wisdom: "Ex obsession! Kung mas bet si ex, dun na siya!", category: GameMode.ADULT },
  { text: "Binibiro na may 'backup' siya pag di kayo nagwork out.", isRedFlag: true, wisdom: "Backup jokes! Hindi nakakatawa ang may kapalit agad!", category: GameMode.TEENS },
  { text: "Nahuli mo na nag-flirt pero 'friendly lang' daw.", isRedFlag: true, wisdom: "Flirting as friendly! Ang friendly may limits, ang flirty wala!", category: GameMode.YOUNG_ADULT },
  { text: "Sinasabi na 'type' niya ang mga taong nakikita niyo. In front of you.", isRedFlag: true, wisdom: "Public typing! Disrespectful to do in front of partner!", category: GameMode.ADULT },
  { text: "Ine-entertain ang advances ng iba 'to not be rude'.", isRedFlag: true, wisdom: "Entertaining attention! May commitment ka, be rude na if needed!", category: GameMode.TEENS },
  { text: "Hindi sinasabi sa iba na taken. 'Di naman nila tinatanong eh'.", isRedFlag: true, wisdom: "Hidden relationship! Should be proactively disclosed!", category: GameMode.YOUNG_ADULT },
  { text: "May ex na 'best friend' na laging kasama. 'Over na kami, friends na lang'.", isRedFlag: true, wisdom: "Ex as bestie! Some ex relationships should have more distance!", category: GameMode.ADULT },
  { text: "Nagagalit pag may kausap kang iba pero siya pwede. Double standard.", isRedFlag: true, wisdom: "Jealousy double standard! Rules should apply to both!", category: GameMode.TEENS },
  { text: "Sinabi ng friend niya na may nilalandi siya. 'Inggit lang yun'.", isRedFlag: true, wisdom: "Friends spilling tea! Usually friends know more than you!", category: GameMode.YOUNG_ADULT },
  { text: "Late umuuwi ng walang explanation. 'Traffic' every single time.", isRedFlag: true, wisdom: "Convenient excuses! Traffic every night? Sus!", category: GameMode.ADULT },
  { text: "Panay comment sa photos ng iba pero ikaw hindi niya nila-like.", isRedFlag: true, wisdom: "Selective engagement! Energy for others, wala para sayo?", category: GameMode.TEENS },
  { text: "Biglang conscious sa itsura lately. Gym, skin care, new wardrobe. Di mo naman birthday.", isRedFlag: true, wisdom: "Sudden glow up! For who? Check the motivation!", category: GameMode.YOUNG_ADULT },
  { text: "Tinago ang message notification pag nakita mong may nagchat sa kanya.", isRedFlag: true, wisdom: "Hiding notifications! Guilty movement yan!", category: GameMode.ADULT },
  { text: "Sinasabi na 'friends lang' pero ang sweet ng chat nila.", isRedFlag: true, wisdom: "Friends with benefits na chats! Emotional cheating territory!", category: GameMode.TEENS },
  { text: "Di pinapakilala sa friends at family. 'Hindi pa tamang time'.", isRedFlag: true, wisdom: "Hidden from circles! When is 'right time'? Never?", category: GameMode.YOUNG_ADULT },

  // Emotional & Mental Health Red Flags (50)
  { text: "Ginagamit ang mental health issues para ma-excuse ang toxic behavior.", isRedFlag: true, wisdom: "Mental health as excuse! Valid ang struggles pero not excuse for abuse!", category: GameMode.ADULT },
  { text: "Pag nagkamali, 'Ganyan talaga ako, di na magbabago' pa proud.", isRedFlag: true, wisdom: "Growth refusal! Walang effort to improve is a choice!", category: GameMode.TEENS },
  { text: "Nagthreatreaten ng self-harm pag ayaw mo sumunod. Emotional hostage.", isRedFlag: true, wisdom: "Threat manipulation! This is abuse, report to professionals!", category: GameMode.YOUNG_ADULT },
  { text: "Laging victim siya sa lahat ng past relationships. 'Lahat sila masama'.", isRedFlag: true, wisdom: "Common denominator! Lahat masama except siya? Hmm...", category: GameMode.ADULT },
  { text: "Binabalewala feelings mo. 'Wala yan, exaggerated lang yan'.", isRedFlag: true, wisdom: "Dismissing feelings! Your emotions are valid!", category: GameMode.TEENS },
  { text: "Mood swings na unpredictable. Walking on eggshells ka lagi.", isRedFlag: true, wisdom: "Unpredictable moods! Home should be safe, not stressful!", category: GameMode.YOUNG_ADULT },
  { text: "Laging nireremind ka ng mga failures mo. 'Tandaan mo noong...'", isRedFlag: true, wisdom: "Failure reminder! Partner uplifts, not tears down!", category: GameMode.ADULT },
  { text: "Binabasa ang diary/journal mo. 'Bakit may tago ka?'", isRedFlag: true, wisdom: "Privacy invasion! Personal space is sacred!", category: GameMode.TEENS },
  { text: "Nagagalit pag di mo ginawa ang expected niya kahit di naman sinabi.", isRedFlag: true, wisdom: "Mind reader expectation! Communicate, don't expect!", category: GameMode.YOUNG_ADULT },
  { text: "Sinisisi ka sa lahat ng problema niya sa buhay.", isRedFlag: true, wisdom: "Blame magnet! You're not responsible for everything wrong in their life!", category: GameMode.ADULT },
  { text: "Pinapahiya ka sa harap ng ibang tao. 'Joke lang naman'.", isRedFlag: true, wisdom: "Public humiliation! Jokes should not embarrass partner!", category: GameMode.TEENS },
  { text: "Inaasar ka about insecurities mo na alam niyang sensitive ka.", isRedFlag: true, wisdom: "Weaponizing insecurities! They should protect these, not exploit!", category: GameMode.YOUNG_ADULT },
  { text: "Laging negatibo. Lahat ng ideas mo, may pero. Lahat ng plano mo, may problema.", isRedFlag: true, wisdom: "Chronic negativity! Energy drainer siya, not supporter!", category: GameMode.ADULT },
  { text: "Mataas ang standards para sayo pero mababa para sa sarili niya.", isRedFlag: true, wisdom: "Hypocrite standards! Same rules should apply to both!", category: GameMode.TEENS },
  { text: "Laging pagod/busy/stressed pag need mo siya pero available pag need niya.", isRedFlag: true, wisdom: "Selective availability! One-way street lang relationship?", category: GameMode.YOUNG_ADULT },
  { text: "Kinokontrol food intake mo. 'Baka tumaba ka, bawasan mo na'.", isRedFlag: true, wisdom: "Food policing! Your body, your food choices!", category: GameMode.ADULT },
  { text: "Pag may achievement ka, may snide comment. 'Madali lang naman yun'.", isRedFlag: true, wisdom: "Achievement downplaying! Celebrate wins, not diminish!", category: GameMode.TEENS },
  { text: "Hindi nakikinig pag may sinasabi ka. 'Ha? Ano ulit?'", isRedFlag: true, wisdom: "Not listening! Basic respect is attention when talking!", category: GameMode.YOUNG_ADULT },
  { text: "Pag ikaw may problem, 'mas malala pa problema ko' ang response.", isRedFlag: true, wisdom: "Problem one-upping! Both problems valid, support each other!", category: GameMode.ADULT },
  { text: "Laging disappointed. Ano man gawin mo, kulang pa rin.", isRedFlag: true, wisdom: "Chronic disappointment! Nothing ever enough? Red flag!", category: GameMode.TEENS },

  // Respect & Treatment Red Flags (50)
  { text: "Binabastos ang trabaho mo. 'Yan ba tawag mong career?'", isRedFlag: true, wisdom: "Job shaming! All honest work deserves respect!", category: GameMode.YOUNG_ADULT },
  { text: "Pag may kasama kayong iba, iba siya makitungo sayo. Cold.", isRedFlag: true, wisdom: "Different treatment with audience! Should be same always!", category: GameMode.ADULT },
  { text: "Hindi nagpapaalam kung saan. 'Bakit, nanay mo ba ako?'", isRedFlag: true, wisdom: "No accountability! Basic courtesy to let partner know whereabouts!", category: GameMode.TEENS },
  { text: "Laging late sa dates. Oras mo parang walang halaga.", isRedFlag: true, wisdom: "Chronic lateness! Time disrespect is respect disrespect!", category: GameMode.YOUNG_ADULT },
  { text: "Nagsasalita tungkol sayo negatively sa harap ng friends niya.", isRedFlag: true, wisdom: "Public bashing! Partner should uplift, not tear down publicly!", category: GameMode.ADULT },
  { text: "Binabasa messages mo sa phone pag di ka nakatingin.", isRedFlag: true, wisdom: "Phone snooping! Privacy violation even in relationships!", category: GameMode.TEENS },
  { text: "Kinukuwestiyon ang decisions mo lagi. 'Sure ka diyan?'", isRedFlag: true, wisdom: "Decision undermining! Trust your partner's judgment!", category: GameMode.YOUNG_ADULT },
  { text: "Hinuhusgahan ang past mo. 'Ganyan ka pala dati?'", isRedFlag: true, wisdom: "Past judging! Everyone has history, focus on present!", category: GameMode.ADULT },
  { text: "Nag-eeyeroll pag may sinasabi ka.", isRedFlag: true, wisdom: "Contempt signals! Eye-rolling is disrespect in body language!", category: GameMode.TEENS },
  { text: "Hindi nagsa-salamat kahit may effort ka. Expected na raw kasi.", isRedFlag: true, wisdom: "No gratitude! Appreciation should be expressed, not assumed!", category: GameMode.YOUNG_ADULT },
  { text: "Siya ang boss lagi. Lahat ng decisions, siya.", isRedFlag: true, wisdom: "One-sided power! Partnership means shared decision-making!", category: GameMode.ADULT },
  { text: "Ikinakahiya ka sa ibang tao. 'Sorry, ganyan talaga siya'.", isRedFlag: true, wisdom: "Public apology for you! Should be proud, not embarrassed!", category: GameMode.TEENS },
  { text: "Nang-aasar about looks mo. 'Tumatanda ka na ah, wrinkles mo'.", isRedFlag: true, wisdom: "Appearance mocking! Partner should make you feel beautiful!", category: GameMode.YOUNG_ADULT },
  { text: "Binabalewala opinyon mo. 'Wala ka namang alam diyan'.", isRedFlag: true, wisdom: "Opinion dismissal! Your views matter in relationship!", category: GameMode.ADULT },
  { text: "Laging interrupt pag nagsasalita ka.", isRedFlag: true, wisdom: "Conversation cutting! Let partner finish speaking!", category: GameMode.TEENS },
  { text: "Hindi nagpa-prioritize sa schedule niya. Lagi kang 'fit in' lang.", isRedFlag: true, wisdom: "Afterthought treatment! Should be priority, not option!", category: GameMode.YOUNG_ADULT },
  { text: "Nireremind ka na 'swerte ka' nakuha siya.", isRedFlag: true, wisdom: "Lucky to have them? Both should feel lucky!", category: GameMode.ADULT },
  { text: "Nangungutya pag may sinabi kang 'stupid' according to them.", isRedFlag: true, wisdom: "Intelligence mocking! No question is stupid in safe relationship!", category: GameMode.TEENS },
  { text: "Hindi binibigyan ng importance ang milestones mo.", isRedFlag: true, wisdom: "Milestone ignoring! Your achievements deserve celebration!", category: GameMode.YOUNG_ADULT },
  { text: "Tinatago ka sa social media. 'Private person ako'.", isRedFlag: true, wisdom: "Social media hiding! Private is one thing, hidden is another!", category: GameMode.ADULT },

  // Social & Family Red Flags (30)
  { text: "Ayaw makisama sa family mo. 'Busy' lagi pag may family event.", isRedFlag: true, wisdom: "Family avoidance! Should make effort to connect with your family!", category: GameMode.TEENS },
  { text: "Nagpaparinig tungkol sa mga kaibigan mo. 'Yung mga friends mo kasi...'", isRedFlag: true, wisdom: "Friend criticism! Attacking support system is isolation tactic!", category: GameMode.YOUNG_ADULT },
  { text: "Gusto niya present sa lahat ng hangout mo. 'Para fair'.", isRedFlag: true, wisdom: "No solo friend time! Healthy to have separate social lives!", category: GameMode.ADULT },
  { text: "Chismis ng chismis about friends at family mo.", isRedFlag: true, wisdom: "Gossip about your people! If gossips about them, gossips about you!", category: GameMode.TEENS },
  { text: "Nag-aaway ang family mo dahil sa kanya. Naghahasik ng gulo.", isRedFlag: true, wisdom: "Family drama creator! Should bring peace, not chaos!", category: GameMode.YOUNG_ADULT },
  { text: "Walang friends. 'Toxic daw lahat' kaya siya na lang.", isRedFlag: true, wisdom: "No friends! If everyone is toxic, check the common denominator!", category: GameMode.ADULT },
  { text: "Kinukumpara ang family mo sa family niya. 'Buti pa kami...'", isRedFlag: true, wisdom: "Family comparison! Each family is different, don't compare!", category: GameMode.TEENS },
  { text: "Ayaw na daw na makipag-hang out ka sa certain friend. 'Bad influence'.", isRedFlag: true, wisdom: "Friend controlling! Your friends are your choice!", category: GameMode.YOUNG_ADULT },
  { text: "Siya lagi ang main character sa events. Attention sa kanya dapat.", isRedFlag: true, wisdom: "Attention seeking! Should share spotlight, not steal it!", category: GameMode.ADULT },
  { text: "Binabastos ang parents mo behind their backs.", isRedFlag: true, wisdom: "Parent disrespect! Respect to elders is basic!", category: GameMode.TEENS },
  { text: "Laging may negative comment sa mga kakilala niyo.", isRedFlag: true, wisdom: "Universal negativity! Negative about everyone, including you eventually!", category: GameMode.YOUNG_ADULT },
  { text: "Hindi niya kayang maging happy for friends mong successful.", isRedFlag: true, wisdom: "Jealous of your friends! Should be happy for your circle!", category: GameMode.ADULT },
  { text: "Kumukuha ng side ng ibang tao laban sayo pag may conflict.", isRedFlag: true, wisdom: "Siding with others! Partner should be on your team!", category: GameMode.TEENS },
  { text: "Ayaw pumunta sa important events mo. 'Nakaka-bore naman yan'.", isRedFlag: true, wisdom: "Event avoidance! Should support your important moments!", category: GameMode.YOUNG_ADULT },
  { text: "Nirereplace ka ng iba pag di ka available. 'May kasama na ako'.", isRedFlag: true, wisdom: "Replacement ready! You're not easily replaceable in relationship!", category: GameMode.ADULT },
  { text: "Kinukwento ang private matters niyo sa friends without consent.", isRedFlag: true, wisdom: "Privacy breach! Couple matters should stay between couple!", category: GameMode.TEENS },
  { text: "Nagseselos sa attention na binibigay mo sa family mo.", isRedFlag: true, wisdom: "Family jealousy! Family is family, different from relationship!", category: GameMode.YOUNG_ADULT },
  { text: "Nagiging competitive with your friends instead of being friends too.", isRedFlag: true, wisdom: "Friend competition! Should befriend your friends, not compete!", category: GameMode.ADULT },
  { text: "Nang-aalila ng friends mo against you pag may away.", isRedFlag: true, wisdom: "Friend manipulation! Fighting fair means no outside allies!", category: GameMode.TEENS },
  { text: "Ayaw mag-effort makisama sa circle mo. 'Di ko sila type'.", isRedFlag: true, wisdom: "Social effort lacking! Partnership includes social integration!", category: GameMode.YOUNG_ADULT },

  // Physical & Boundary Red Flags (20)
  { text: "Nag-demand ng access sa location mo 24/7. 'Para alam ko safe ka'.", isRedFlag: true, wisdom: "Location stalking! Safety check is fine, surveillance is not!", category: GameMode.ADULT },
  { text: "Pinipilit ka mag-physical kahit di ka ready. 'Ikaw naman kasi...'", isRedFlag: true, wisdom: "Consent pushing! No means no, period!", category: GameMode.TEENS },
  { text: "Binabagsak ang gamit pag galit. Violent tendencies.", isRedFlag: true, wisdom: "Object violence! Today objects, tomorrow... be careful!", category: GameMode.YOUNG_ADULT },
  { text: "Kinukontrol ang damit mo. 'Revealing yan, palitan mo'.", isRedFlag: true, wisdom: "Clothing control! Your body, your clothes!", category: GameMode.ADULT },
  { text: "Hindi respectful ng personal space mo. Always on you.", isRedFlag: true, wisdom: "Space invasion! Everyone needs breathing room!", category: GameMode.TEENS },
  { text: "Grips too tight pag nag-aaway. 'Para di ka umalis'.", isRedFlag: true, wisdom: "Physical restraint! Red flag for physical abuse!", category: GameMode.YOUNG_ADULT },
  { text: "Hinihila ka pag gusto niyang umalis somewhere.", isRedFlag: true, wisdom: "Physical force to leave! Should ask, not pull!", category: GameMode.ADULT },
  { text: "Threatening body language pag galit. Looming over you.", isRedFlag: true, wisdom: "Intimidation posture! Physical threat is abuse!", category: GameMode.TEENS },
  { text: "Blocks the doorway pag ayaw kang paalisin.", isRedFlag: true, wisdom: "Exit blocking! Trapping is a form of abuse!", category: GameMode.YOUNG_ADULT },
  { text: "Nagpupumilit sa mga intimate details ng past mo. 'May karapatan akong malaman'.", isRedFlag: true, wisdom: "Past interrogation! You don't owe them your history!", category: GameMode.ADULT },

  // ========== GREEN FLAGS (150) ==========
  
  // Communication Green Flags (30)
  { text: "Pag may concern, directly sinasabi nang hindi accusatory. 'I feel worried when...'", isRedFlag: false, wisdom: "I-statements! Healthy communication uses feelings, not blame!", category: GameMode.TEENS },
  { text: "Nag-aask kung okay ba mag-voice out ng opinion bago mag-rant.", isRedFlag: false, wisdom: "Permission to share! Asks if you have capacity to listen!", category: GameMode.YOUNG_ADULT },
  { text: "Active listener. Repeats back what you said para sure na understood.", isRedFlag: false, wisdom: "Reflective listening! Makes sure they truly understand you!", category: GameMode.ADULT },
  { text: "Nag-eexplain calmly kahit heated ang situation.", isRedFlag: false, wisdom: "Calm in conflict! Maturity to stay calm under pressure!", category: GameMode.TEENS },
  { text: "Nagsasabi ng 'I'm not in the right headspace, can we talk later?'", isRedFlag: false, wisdom: "Self-awareness! Knows when not capable of good conversation!", category: GameMode.YOUNG_ADULT },
  { text: "Nag-aadmit pag may mali at nag-aadjust ng behavior.", isRedFlag: false, wisdom: "Growth mindset! Admits fault and actually changes!", category: GameMode.ADULT },
  { text: "Tinanong kung ano ang love language mo at nag-effort aralin.", isRedFlag: false, wisdom: "Love language learning! Wants to love you in your way!", category: GameMode.TEENS },
  { text: "Nagiging curious about thoughts mo, not just your activities.", isRedFlag: false, wisdom: "Deep interest! Wants to know your mind, not just schedule!", category: GameMode.YOUNG_ADULT },
  { text: "Nag-check in regularly. 'Kamusta ka talaga?'", isRedFlag: false, wisdom: "Genuine check-ins! Cares about your wellbeing consistently!", category: GameMode.ADULT },
  { text: "Shares vulnerable moments with you. Opens up about fears.", isRedFlag: false, wisdom: "Vulnerability sharing! Trusts you with sensitive topics!", category: GameMode.TEENS },
  { text: "Validates feelings even if doesn't fully understand. 'That makes sense'.", isRedFlag: false, wisdom: "Feeling validation! Accepts emotions without judgment!", category: GameMode.YOUNG_ADULT },
  { text: "Uses 'we' language for problems. 'What can we do about this?'", isRedFlag: false, wisdom: "Team language! Approaches problems as partners!", category: GameMode.ADULT },
  { text: "Apologizes without 'but'. 'I'm sorry I hurt you'.", isRedFlag: false, wisdom: "Clean apology! Sorry with no conditions or blame!", category: GameMode.TEENS },
  { text: "Asks about your day and actually remembers details.", isRedFlag: false, wisdom: "Attentive listening! Remembers what you share!", category: GameMode.YOUNG_ADULT },
  { text: "Gives full attention during important conversations. Phone away.", isRedFlag: false, wisdom: "Undivided attention! Prioritizes focus on you!", category: GameMode.ADULT },
  { text: "Expresses gratitude for small things. 'Thanks for that'.", isRedFlag: false, wisdom: "Regular appreciation! Doesn't take efforts for granted!", category: GameMode.TEENS },
  { text: "Discusses future together naturally. 'When we...'", isRedFlag: false, wisdom: "Future talk! Sees you in their future naturally!", category: GameMode.YOUNG_ADULT },
  { text: "Admits 'I don't know' when uncertain instead of pretending.", isRedFlag: false, wisdom: "Honest uncertainty! Doesn't pretend to know everything!", category: GameMode.ADULT },
  { text: "Fights fair. Sticks to issue, no personal attacks.", isRedFlag: false, wisdom: "Fair fighting! Argues to solve, not to hurt!", category: GameMode.TEENS },
  { text: "Respects your need for space during arguments.", isRedFlag: false, wisdom: "Space respect! Allows processing time when needed!", category: GameMode.YOUNG_ADULT },

  // Trust & Support Green Flags (30)
  { text: "Celebrates your wins genuinely. First to congratulate.", isRedFlag: false, wisdom: "Win celebration! Genuine happiness for your success!", category: GameMode.ADULT },
  { text: "Trusts you without needing constant proof.", isRedFlag: false, wisdom: "Trust without proof! Doesn't need surveillance!", category: GameMode.TEENS },
  { text: "Supportive of your friendships with all genders.", isRedFlag: false, wisdom: "Friend trust! Secure enough not to be threatened!", category: GameMode.YOUNG_ADULT },
  { text: "Encourages your goals even if inconvenient for them.", isRedFlag: false, wisdom: "Goal support! Prioritizes your growth over convenience!", category: GameMode.ADULT },
  { text: "Keeps promises and follows through.", isRedFlag: false, wisdom: "Promise keeping! Words match actions!", category: GameMode.TEENS },
  { text: "Doesn't check your phone. Respects privacy.", isRedFlag: false, wisdom: "Privacy respect! Trusts without surveillance!", category: GameMode.YOUNG_ADULT },
  { text: "Speaks highly of you when you're not around.", isRedFlag: false, wisdom: "Positive representation! Same good words behind your back!", category: GameMode.ADULT },
  { text: "Takes your concerns seriously even if seems small to them.", isRedFlag: false, wisdom: "Concern taking! Values what matters to you!", category: GameMode.TEENS },
  { text: "Defends you when others criticize unfairly.", isRedFlag: false, wisdom: "Defense mode! Stands up for you when needed!", category: GameMode.YOUNG_ADULT },
  { text: "Consistent behavior whether witnessed or not.", isRedFlag: false, wisdom: "Consistency! Same person everywhere!", category: GameMode.ADULT },
  { text: "Honest even when truth is hard. Gentle but truthful.", isRedFlag: false, wisdom: "Honest kindness! Truth told with care!", category: GameMode.TEENS },
  { text: "Reliable. Shows up when they say they will.", isRedFlag: false, wisdom: "Reliability! Can count on them!", category: GameMode.YOUNG_ADULT },
  { text: "Gives benefit of doubt before assuming worst.", isRedFlag: false, wisdom: "Positive assumption! Doesn't jump to bad conclusions!", category: GameMode.ADULT },
  { text: "Transparent about their life. Shares naturally.", isRedFlag: false, wisdom: "Natural transparency! Open without prompting!", category: GameMode.TEENS },
  { text: "Remembers important dates. Birthday, anniversary.", isRedFlag: false, wisdom: "Date memory! Shows you're on their mind!", category: GameMode.YOUNG_ADULT },
  { text: "Introduces you to friends and family with pride.", isRedFlag: false, wisdom: "Proud introduction! Wants their people to know you!", category: GameMode.ADULT },
  { text: "Admits when wrong to others, not just you.", isRedFlag: false, wisdom: "Public accountability! Honest with everyone!", category: GameMode.TEENS },
  { text: "Doesn't keep score on favors or gifts.", isRedFlag: false, wisdom: "No scorekeeping! Gives freely without expectation!", category: GameMode.YOUNG_ADULT },
  { text: "Happy when good things happen to you. No jealousy.", isRedFlag: false, wisdom: "Pure happiness! Your wins are their joy!", category: GameMode.ADULT },
  { text: "Respects your boundaries without pushing.", isRedFlag: false, wisdom: "Boundary respect! Accepts limits without pressure!", category: GameMode.TEENS },

  // Emotional Intelligence Green Flags (30)
  { text: "Manages own emotions well. Doesn't take stress out on you.", isRedFlag: false, wisdom: "Emotional regulation! Handles self before projecting!", category: GameMode.YOUNG_ADULT },
  { text: "Shows empathy in hard times. 'That sounds really tough'.", isRedFlag: false, wisdom: "Empathy showing! Feels with you!", category: GameMode.ADULT },
  { text: "Knows when to give space vs when to be present.", isRedFlag: false, wisdom: "Intuitive support! Reads what you need!", category: GameMode.TEENS },
  { text: "Doesn't hold grudges. Moves forward after resolution.", isRedFlag: false, wisdom: "Forgiveness! Doesn't bring up past after resolved!", category: GameMode.YOUNG_ADULT },
  { text: "Takes responsibility for own happiness. Not dependent on you.", isRedFlag: false, wisdom: "Self-responsibility! Complete person alone!", category: GameMode.ADULT },
  { text: "Encourages your self-care. 'Take time for yourself'.", isRedFlag: false, wisdom: "Self-care encourager! Wants you to thrive!", category: GameMode.TEENS },
  { text: "Handles disappointment maturely. No tantrums or guilt trips.", isRedFlag: false, wisdom: "Disappointment handling! Mature reaction to setbacks!", category: GameMode.YOUNG_ADULT },
  { text: "Open to therapy or counseling if needed.", isRedFlag: false, wisdom: "Help-seeking! Willing to work on issues professionally!", category: GameMode.ADULT },
  { text: "Notices when you're off and gently asks about it.", isRedFlag: false, wisdom: "Emotional awareness! Notices your moods!", category: GameMode.TEENS },
  { text: "Celebrates small wins too, not just big achievements.", isRedFlag: false, wisdom: "Small win celebration! Appreciates daily victories!", category: GameMode.YOUNG_ADULT },
  { text: "Expresses emotions healthily. Cries, laughs, shares.", isRedFlag: false, wisdom: "Emotional expression! Not emotionally blocked!", category: GameMode.ADULT },
  { text: "Supports your mental health journey.", isRedFlag: false, wisdom: "Mental health support! Encourages your wellbeing!", category: GameMode.TEENS },
  { text: "Deals with conflict constructively. Seeks resolution.", isRedFlag: false, wisdom: "Constructive conflict! Aims to solve, not win!", category: GameMode.YOUNG_ADULT },
  { text: "Secure enough to admit insecurities.", isRedFlag: false, wisdom: "Insecurity admission! Humble about struggles!", category: GameMode.ADULT },
  { text: "Makes you feel safe to be vulnerable.", isRedFlag: false, wisdom: "Safety creation! Welcomes your raw moments!", category: GameMode.TEENS },
  { text: "Handles stress without lashing out.", isRedFlag: false, wisdom: "Stress management! Doesn't make you the target!", category: GameMode.YOUNG_ADULT },
  { text: "Shows affection consistently, not just when convenient.", isRedFlag: false, wisdom: "Consistent affection! Love shown regularly!", category: GameMode.ADULT },
  { text: "Patient with your growth and learning.", isRedFlag: false, wisdom: "Patience with growth! Allows you to develop!", category: GameMode.TEENS },
  { text: "Celebrates your wins as own wins. Team mentality.", isRedFlag: false, wisdom: "Team celebration! 'We' wins together!", category: GameMode.YOUNG_ADULT },
  { text: "Creates repair after disagreements. Reaches out first.", isRedFlag: false, wisdom: "Repair initiation! Starts reconciliation!", category: GameMode.ADULT },

  // Respect & Consideration Green Flags (30)
  { text: "Asks before posting photos of you. 'Is this okay to share?'", isRedFlag: false, wisdom: "Photo consent! Respects your digital image!", category: GameMode.TEENS },
  { text: "Remembers your preferences. Orders your coffee right.", isRedFlag: false, wisdom: "Preference memory! Pays attention to likes!", category: GameMode.YOUNG_ADULT },
  { text: "Gives you say in decisions that affect both of you.", isRedFlag: false, wisdom: "Shared decisions! Your input matters!", category: GameMode.ADULT },
  { text: "On time or communicates if running late.", isRedFlag: false, wisdom: "Time respect! Values your schedule!", category: GameMode.TEENS },
  { text: "Doesn't pressure you into things you're not ready for.", isRedFlag: false, wisdom: "Pace respect! Lets you go at your speed!", category: GameMode.YOUNG_ADULT },
  { text: "Respects your opinions even when disagrees.", isRedFlag: false, wisdom: "Opinion respect! Disagrees respectfully!", category: GameMode.ADULT },
  { text: "Never puts you down, especially in front of others.", isRedFlag: false, wisdom: "Dignity protection! Never embarrasses you!", category: GameMode.TEENS },
  { text: "Asks about your comfort level regularly.", isRedFlag: false, wisdom: "Comfort checking! Cares about your ease!", category: GameMode.YOUNG_ADULT },
  { text: "Proud to be with you publicly.", isRedFlag: false, wisdom: "Public pride! Happy to be seen with you!", category: GameMode.ADULT },
  { text: "Respects your family even if different from their own.", isRedFlag: false, wisdom: "Family respect! Accepts your background!", category: GameMode.TEENS },
  { text: "Celebrates your individuality. Loves what makes you different.", isRedFlag: false, wisdom: "Individuality love! Treasures your uniqueness!", category: GameMode.YOUNG_ADULT },
  { text: "Encourages your hobbies and interests.", isRedFlag: false, wisdom: "Hobby support! Wants you to have passions!", category: GameMode.ADULT },
  { text: "Treats service workers with respect and kindness.", isRedFlag: false, wisdom: "Universal respect! Kind to everyone!", category: GameMode.TEENS },
  { text: "Knows when to step back and let you handle things.", isRedFlag: false, wisdom: "Autonomy respect! Trusts your capability!", category: GameMode.YOUNG_ADULT },
  { text: "Makes space for your needs, not just their own.", isRedFlag: false, wisdom: "Need prioritizing! Your needs matter too!", category: GameMode.ADULT },
  { text: "Appreciates effort even if result isn't perfect.", isRedFlag: false, wisdom: "Effort appreciation! Values the try!", category: GameMode.TEENS },
  { text: "Checks in before making plans that affect you.", isRedFlag: false, wisdom: "Plan checking! Considers your schedule!", category: GameMode.YOUNG_ADULT },
  { text: "Celebrates your career or education achievements.", isRedFlag: false, wisdom: "Achievement celebration! Proud of your success!", category: GameMode.ADULT },
  { text: "Asks about your comfort in social situations.", isRedFlag: false, wisdom: "Social comfort! Cares about your ease around others!", category: GameMode.TEENS },
  { text: "Balances time between you and other responsibilities.", isRedFlag: false, wisdom: "Balance maintenance! Manages priorities well!", category: GameMode.YOUNG_ADULT },

  // Growth & Future Green Flags (30)
  { text: "Has goals and works toward them consistently.", isRedFlag: false, wisdom: "Goal pursuit! Ambitious and driven!", category: GameMode.ADULT },
  { text: "Open to learning and improving themselves.", isRedFlag: false, wisdom: "Growth mindset! Always developing!", category: GameMode.TEENS },
  { text: "Discusses future naturally without pressure.", isRedFlag: false, wisdom: "Future planning! Sees long-term with you!", category: GameMode.YOUNG_ADULT },
  { text: "Has healthy habits or works on developing them.", isRedFlag: false, wisdom: "Healthy living! Takes care of self!", category: GameMode.ADULT },
  { text: "Financially responsible or working to become so.", isRedFlag: false, wisdom: "Financial growth! Building stability!", category: GameMode.TEENS },
  { text: "Supports your personal development.", isRedFlag: false, wisdom: "Development support! Wants you to grow!", category: GameMode.YOUNG_ADULT },
  { text: "Has interests and hobbies of their own.", isRedFlag: false, wisdom: "Independent interests! Full person on own!", category: GameMode.ADULT },
  { text: "Plans for future but enjoys present.", isRedFlag: false, wisdom: "Balanced timeline! Dreams but lives now too!", category: GameMode.TEENS },
  { text: "Willing to compromise for relationship growth.", isRedFlag: false, wisdom: "Compromise willing! Adjusts for both!", category: GameMode.YOUNG_ADULT },
  { text: "Invests in the relationship consistently.", isRedFlag: false, wisdom: "Relationship investment! Puts in effort!", category: GameMode.ADULT },
  { text: "Talks about including you in future plans.", isRedFlag: false, wisdom: "Future including! You're in their vision!", category: GameMode.TEENS },
  { text: "Works on weaknesses when identified.", isRedFlag: false, wisdom: "Weakness working! Self-improvement oriented!", category: GameMode.YOUNG_ADULT },
  { text: "Makes sacrifices for mutual goals.", isRedFlag: false, wisdom: "Mutual sacrifice! Gives for shared dreams!", category: GameMode.ADULT },
  { text: "Discusses finances openly and honestly.", isRedFlag: false, wisdom: "Financial openness! Transparent about money!", category: GameMode.TEENS },
  { text: "Wants to grow together, not just individually.", isRedFlag: false, wisdom: "Together growth! Partnership evolution!", category: GameMode.YOUNG_ADULT },
  { text: "Has realistic expectations about life and love.", isRedFlag: false, wisdom: "Realistic views! Grounded expectations!", category: GameMode.ADULT },
  { text: "Values experiences and memories over material things.", isRedFlag: false, wisdom: "Experience valuing! Prioritizes moments!", category: GameMode.TEENS },
  { text: "Takes feedback well and uses it to improve.", isRedFlag: false, wisdom: "Feedback receptive! Uses input positively!", category: GameMode.YOUNG_ADULT },
  { text: "Maintains own identity while being in relationship.", isRedFlag: false, wisdom: "Identity maintenance! Still self within us!", category: GameMode.ADULT },
  { text: "Excited about building a life together.", isRedFlag: false, wisdom: "Life-building excitement! Enthusiastic about future!", category: GameMode.TEENS }
];